"""add_entity_drafts

Revision ID: 16b818ea89fc
Revises: bad6350ef9d2
Create Date: 2026-04-14 19:22:25.834291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '16b818ea89fc'
down_revision: Union[str, Sequence[str], None] = 'bad6350ef9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_text_drafts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_discarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_text_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_text_drafts_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_text_drafts_entity_id'), ['entity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_text_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_text_drafts_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_text_drafts_collection_id'))

    op.drop_table('entity_text_drafts')
    # ### end Alembic commands ###
