"""add generated_texts and entity_contents and update entity_type enum

Revision ID: 3f4b89444533
Revises: 77f2396a5714
Create Date: 2026-04-22 20:45:05.131566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '3f4b89444533'
down_revision: Union[str, Sequence[str], None] = '77f2396a5714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_texts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('backstory', 'extended_description', 'scene', 'chapter', name='contentcategory'), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('raw_content', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_texts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_texts_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_texts_entity_id'), ['entity_id'], unique=False)

    op.create_table('entity_contents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('generated_text_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('backstory', 'extended_description', 'scene', 'chapter', name='contentcategory'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'discarded', name='contentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['generated_text_id'], ['generated_texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_contents_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_contents_entity_id'), ['entity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_contents_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_contents_collection_id'))

    op.drop_table('entity_contents')
    with op.batch_alter_table('generated_texts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_texts_entity_id'))
        batch_op.drop_index(batch_op.f('ix_generated_texts_collection_id'))

    op.drop_table('generated_texts')
    # ### end Alembic commands ###
