"""add_updated_by_audit_trail

Revision ID: 44e100e56077
Revises: 1064fb419cc5
Create Date: 2026-05-10 21:46:32.882181

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "44e100e56077"
down_revision: Union[str, Sequence[str], None] = "1064fb419cc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_by", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True
            )
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "content_hash",
                sqlmodel.sql.sqltypes.AutoString(length=64),
                nullable=True,
            )
        )

    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_by", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True
            )
        )

    with op.batch_alter_table("entity_contents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_by", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entity_contents", schema=None) as batch_op:
        batch_op.drop_column("updated_by")

    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.drop_column("updated_by")

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_column("content_hash")

    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.drop_column("updated_by")

    # ### end Alembic commands ###
