"""enrich moderation_log with context fields

Revision ID: 6413adc4bb9c
Revises: a1b2c3d4e5f6
Create Date: 2026-05-17 10:01:11.886608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '6413adc4bb9c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
        batch_op.add_column(sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True))
        batch_op.add_column(sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
        batch_op.add_column(sa.Column('pattern_matched', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation_log', schema=None) as batch_op:
        batch_op.drop_column('pattern_matched')
        batch_op.drop_column('operation')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('collection_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
