"""Checkpoint

Revision ID: 721158ba3166
Revises: 
Create Date: 2026-05-04 07:26:07.786532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '721158ba3166'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_name'), ['name'], unique=True)

    op.create_table('moderation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('processing', 'completed', 'failed', name='documentstatus'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_collection_id'), ['collection_id'], unique=False)

    op.create_table('entities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('character', 'creature', 'faction', 'location', 'item', name='entitytype'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'name', name='uq_entity_collection_name')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_type'), ['type'], unique=False)

    op.create_table('generated_texts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('raw_content', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_texts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_texts_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_texts_entity_id'), ['entity_id'], unique=False)

    op.create_table('entity_contents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('generated_text_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('backstory', 'extended_description', 'scene', 'chapter', name='contentcategory'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'discarded', name='contentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['generated_text_id'], ['generated_texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_contents_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_contents_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_contents_generated_text_id'), ['generated_text_id'], unique=False)

    op.create_table('image_generations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('auto_prompt', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('final_prompt', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('prompt_token_count', sa.Integer(), nullable=False),
    sa.Column('prompt_source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('backend', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['entity_contents.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_generations_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_generations_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_generations_entity_id'), ['entity_id'], unique=False)

    op.create_table('image_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('generation_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['image_generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_records_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_records_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_records_generation_id'), ['generation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_records_generation_id'))
        batch_op.drop_index(batch_op.f('ix_image_records_entity_id'))
        batch_op.drop_index(batch_op.f('ix_image_records_collection_id'))

    op.drop_table('image_records')
    with op.batch_alter_table('image_generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_generations_entity_id'))
        batch_op.drop_index(batch_op.f('ix_image_generations_content_id'))
        batch_op.drop_index(batch_op.f('ix_image_generations_collection_id'))

    op.drop_table('image_generations')
    with op.batch_alter_table('entity_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_contents_generated_text_id'))
        batch_op.drop_index(batch_op.f('ix_entity_contents_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_contents_collection_id'))

    op.drop_table('entity_contents')
    with op.batch_alter_table('generated_texts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_texts_entity_id'))
        batch_op.drop_index(batch_op.f('ix_generated_texts_collection_id'))

    op.drop_table('generated_texts')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_type'))
        batch_op.drop_index(batch_op.f('ix_entities_collection_id'))

    op.drop_table('entities')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_collection_id'))

    op.drop_table('documents')
    op.drop_table('moderation_log')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_name'))

    op.drop_table('collections')
    # ### end Alembic commands ###
