"""enum_types_consistency

Revision ID: 872f2cf02838
Revises: 4a82125fc02f
Create Date: 2026-04-14 11:45:20.434401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "872f2cf02838"
down_revision: Union[str, Sequence[str], None] = "4a82125fc02f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.Enum("completed", "failed", name="documentstatus"),
            existing_nullable=False,
        )

    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.Enum("character", "scene", "faction", "item", name="entitytype"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.Enum(
                "character", "scene", "faction", "item", name="entitytype"
            ),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum("completed", "failed", name="documentstatus"),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
