"""entity_name_unique_per_collection

Revision ID: 8933b2e3a24a
Revises: ce94b03b9981
Create Date: 2026-04-23 16:42:54.201621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '8933b2e3a24a'
down_revision: Union[str, Sequence[str], None] = 'ce94b03b9981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_entity_collection_name', ['collection_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_entity_collection_name', type_='unique')

    # ### end Alembic commands ###
