"""expand_image_prompt_columns_to_2000

Revision ID: 942c4e2fc4ac
Revises: aa8786765549
Create Date: 2026-05-14 23:11:36.176074

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '942c4e2fc4ac'
down_revision: str | Sequence[str] | None = 'aa8786765549'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_generations', schema=None) as batch_op:
        batch_op.alter_column('auto_prompt',
               existing_type=sa.VARCHAR(length=1000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2000),
               existing_nullable=False)
        batch_op.alter_column('final_prompt',
               existing_type=sa.VARCHAR(length=1000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_generations', schema=None) as batch_op:
        batch_op.alter_column('final_prompt',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.alter_column('auto_prompt',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
