"""Checkpoint

Revision ID: a7896e41ad17
Revises: 721158ba3166
Create Date: 2026-05-04 09:35:51.641414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "a7896e41ad17"
down_revision: Union[str, Sequence[str], None] = "721158ba3166"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image_generations", schema=None) as batch_op:
        batch_op.drop_column("truncated")
        batch_op.drop_column("prompt_source")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image_generations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("prompt_source", sa.VARCHAR(length=50), nullable=False)
        )
        batch_op.add_column(sa.Column("truncated", sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
