"""add model_used to generated_texts

Revision ID: aa8786765549
Revises: 2e5cf1cded95
Create Date: 2026-05-14 11:12:20.241298

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa8786765549"
down_revision: str | Sequence[str] | None = "2e5cf1cded95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generated_texts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model_used", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generated_texts", schema=None) as batch_op:
        batch_op.drop_column("model_used")

    # ### end Alembic commands ###
