"""add image_url to image_records

Revision ID: b32e6ed9c093
Revises: 7af798a2428f
Create Date: 2026-05-03 22:42:02.435004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'b32e6ed9c093'
down_revision: Union[str, Sequence[str], None] = '7af798a2428f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_records', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
