"""Checkpoint

Revision ID: d95386bcf774
Revises: e011b055990d
Create Date: 2026-05-13 07:34:30.410447

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d95386bcf774"
down_revision: Union[str, Sequence[str], None] = "e011b055990d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
