"""Checkpoint

Revision ID: e8c699c765e5
Revises:
Create Date: 2026-04-29 16:39:56.651515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "e8c699c765e5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_collections_name"), ["name"], unique=True)

    op.create_table(
        "documents",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column(
            "filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "file_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("processing", "completed", "failed", name="documentstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_documents_collection_id"), ["collection_id"], unique=False
        )

    op.create_table(
        "entities",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "character",
                "creature",
                "faction",
                "location",
                "item",
                name="entitytype",
            ),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection_id", "name", name="uq_entity_collection_name"),
    )
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entities_collection_id"), ["collection_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_entities_type"), ["type"], unique=False)

    op.create_table(
        "generated_texts",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column(
            "category", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "query", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False
        ),
        sa.Column(
            "raw_content",
            sqlmodel.sql.sqltypes.AutoString(length=10000),
            nullable=False,
        ),
        sa.Column("sources_count", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("generated_texts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_generated_texts_collection_id"),
            ["collection_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_generated_texts_entity_id"), ["entity_id"], unique=False
        )

    op.create_table(
        "entity_contents",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("generated_text_id", sa.String(length=36), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "backstory",
                "extended_description",
                "scene",
                "chapter",
                name="contentcategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "content", sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "confirmed", "discarded", name="contentstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["generated_text_id"],
            ["generated_texts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("entity_contents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entity_contents_collection_id"),
            ["collection_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_entity_contents_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_entity_contents_generated_text_id"),
            ["generated_text_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entity_contents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entity_contents_generated_text_id"))
        batch_op.drop_index(batch_op.f("ix_entity_contents_entity_id"))
        batch_op.drop_index(batch_op.f("ix_entity_contents_collection_id"))

    op.drop_table("entity_contents")
    with op.batch_alter_table("generated_texts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generated_texts_entity_id"))
        batch_op.drop_index(batch_op.f("ix_generated_texts_collection_id"))

    op.drop_table("generated_texts")
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entities_type"))
        batch_op.drop_index(batch_op.f("ix_entities_collection_id"))

    op.drop_table("entities")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_collection_id"))

    op.drop_table("documents")
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collections_name"))

    op.drop_table("collections")
    # ### end Alembic commands ###
