# Backward compatibility - re-exports from exceptions
from app.core.exceptions import (
    DuplicateEntityNameError,
    DuplicateCollectionNameError,
    ContentNotAllowedError,
    NoContextAvailableError,
    ContentNotConfirmedError,
    PendingLimitExceededError,
    UnsupportedFileTypeError,
    FileTooLargeError,
    MissingFilenameError,
    DocumentExtractionError,
    DatabaseError,
    InvalidCategoryError,
    VectorStoreError,
    ContentDiscardedError,
    ContentNotShareableError,
    GeneratedContentBlockedError,
    DocumentNotRetryableError,
)
